// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

use crate::consumer::fraud::AddressInformation;
use crate::consumer::fraud::DomainInformation;
use serde::{Deserialize, Serialize};

/// RiskRequest: Request type for `Email.risk`.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct RiskRequest {
    /// email_address: The email address to check.
    pub email_address: String,
}
/// RiskResponse: Response type for `Email.risk`.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct RiskResponse {
    /// request_id: Globally unique UUID that is returned with every API call. This value is important to log
    /// for debugging purposes; we may ask for this value to help identify a specific API call when helping you
    /// debug an issue.
    pub request_id: String,
    /// address_information: Information about the email address.
    pub address_information: AddressInformation,
    /// domain_information: Information about the email domain.
    pub domain_information: DomainInformation,
    /// action: The suggested action based on the attributes of the email address. The available actions are:
    ///   * `ALLOW` - This email is most likely safe to send to and not fraudulent.
    ///   * `BLOCK` - This email is invalid or exhibits signs of fraud. We recommend blocking the end user.
    ///   * `CHALLENGE` - This email has some potentially fraudulent attributes. We recommend increased friction
    /// such as 2FA or other forms of extended user verification before allowing the privileged action to
    /// proceed.
    ///
    pub action: RiskResponseAction,
    /// risk_score: A score from 0 to 100 indicating how risky the email is. 100 is the most risky.
    pub risk_score: i32,
    /// status_code: The HTTP status code of the response. Stytch follows standard HTTP response status code
    /// patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
    /// are server errors.
    #[serde(with = "http_serde::status_code")]
    pub status_code: http::StatusCode,
}

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub enum RiskResponseAction {
    #[serde(rename = "ALLOW")]
    #[default]
    ALLOW,
    #[serde(rename = "CHALLENGE")]
    CHALLENGE,
    #[serde(rename = "BLOCK")]
    BLOCK,
}

pub struct Email {
    http_client: crate::client::Client,
}

impl Email {
    pub fn new(http_client: crate::client::Client) -> Self {
        Self {
            http_client: http_client.clone(),
        }
    }

    pub async fn risk(&self, body: RiskRequest) -> crate::Result<RiskResponse> {
        let path = String::from("/v1/email/risk");
        self.http_client
            .send(crate::Request {
                method: http::Method::POST,
                path,
                body,
            })
            .await
    }
}
