// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

use crate::b2b::mfa::MfaRequired;
use crate::b2b::organizations::Member;
use crate::b2b::organizations::Organization;
use crate::b2b::sessions::MemberSession;
use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct AuthenticateRequest {
    pub token: String,
}
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct AuthenticateResponse {
    pub request_id: String,
    pub member_id: String,
    pub organization_id: String,
    pub member: Member,
    pub session_token: String,
    pub session_jwt: String,
    pub organization: Organization,
    pub intermediate_session_token: String,
    pub member_authenticated: bool,
    #[serde(with = "http_serde::status_code")]
    pub status_code: http::StatusCode,
    pub member_session: std::option::Option<MemberSession>,
    pub mfa_required: std::option::Option<MfaRequired>,
}

pub struct Impersonation {
    http_client: crate::client::Client,
}

impl Impersonation {
    pub fn new(http_client: crate::client::Client) -> Self {
        Self {
            http_client: http_client.clone(),
        }
    }

    pub async fn authenticate(
        &self,
        body: AuthenticateRequest,
    ) -> crate::Result<AuthenticateResponse> {
        let path = String::from("/v1/b2b/impersonation/authenticate");
        self.http_client
            .send(crate::Request {
                method: http::Method::POST,
                path,
                body,
            })
            .await
    }
}
