// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

use serde::{Deserialize, Serialize};

/// Policy:
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Policy {
    /// roles: An array of [Role objects](https://stytch.com/docs/b2b/api/rbac-role-object).
    pub roles: std::vec::Vec<PolicyRole>,
    /// resources: An array of [Resource objects](https://stytch.com/docs/b2b/api/rbac-resource-object).
    pub resources: std::vec::Vec<PolicyResource>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PolicyResource {
    pub resource_id: String,
    pub description: String,
    pub actions: std::vec::Vec<String>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PolicyRole {
    pub role_id: String,
    pub description: String,
    pub permissions: std::vec::Vec<PolicyRolePermission>,
}

#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PolicyRolePermission {
    pub resource_id: String,
    pub actions: std::vec::Vec<String>,
}

/// PolicyRequest: Request type for `RBAC.policy`.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct PolicyRequest {}

/// PolicyResponse: Response type for `RBAC.policy`.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct PolicyResponse {
    /// request_id: Globally unique UUID that is returned with every API call. This value is important to log
    /// for debugging purposes; we may ask for this value to help identify a specific API call when helping you
    /// debug an issue.
    pub request_id: String,
    /// status_code: The HTTP status code of the response. Stytch follows standard HTTP response status code
    /// patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
    /// are server errors.
    #[serde(with = "http_serde::status_code")]
    pub status_code: http::StatusCode,
    /// policy: The RBAC Policy document that contains all defined Roles and Resources – which are managed in
    /// the [Dashboard](/dashboard). Read more about these entities and how they work in our
    /// [RBAC overview](https://stytch.com/docs/b2b/guides/rbac/overview).
    pub policy: std::option::Option<Policy>,
}

pub struct RBAC {
    http_client: crate::client::Client,
}

impl RBAC {
    pub fn new(http_client: crate::client::Client) -> Self {
        Self {
            http_client: http_client.clone(),
        }
    }

    pub async fn policy(&self, body: PolicyRequest) -> crate::Result<PolicyResponse> {
        let path = String::from("/v1/b2b/rbac/policy");
        self.http_client
            .send(crate::Request {
                method: http::Method::GET,
                path,
                body,
            })
            .await
    }
}
