// !!!
// WARNING: This file is autogenerated
// Only modify code within MANUAL() sections
// or your changes may be overwritten later!
// !!!

use crate::b2b::rbac::OrgPolicy;
use percent_encoding;
use serde::{Deserialize, Serialize};
use serde_urlencoded;

/// GetOrgPolicyRequest: Request type for `Organizations.get_org_policy`.
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct GetOrgPolicyRequest {
    /// organization_id: Globally unique UUID that identifies a specific Organization. The `organization_id` is
    /// critical to perform operations on an Organization, so be sure to preserve this value. You may also use
    /// the organization_slug or organization_external_id here as a convenience.
    pub organization_id: String,
}
/// GetOrgPolicyResponse: Response type for `Organizations.get_org_policy`.
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct GetOrgPolicyResponse {
    /// request_id: Globally unique UUID that is returned with every API call. This value is important to log
    /// for debugging purposes; we may ask for this value to help identify a specific API call when helping you
    /// debug an issue.
    pub request_id: String,
    /// status_code: The HTTP status code of the response. Stytch follows standard HTTP response status code
    /// patterns, e.g. 2XX values equate to success, 3XX values are redirects, 4XX are client errors, and 5XX
    /// are server errors.
    #[serde(with = "http_serde::status_code")]
    pub status_code: http::StatusCode,
    /// org_policy: The organization-specific RBAC Policy that contains roles defined for this organization.
    /// Organization policies supplement the project-level RBAC policy with additional roles that are specific
    /// to the organization.
    pub org_policy: std::option::Option<OrgPolicy>,
}
#[derive(Serialize, Deserialize, Debug, Clone, Default)]
pub struct SetOrgPolicyRequest {
    pub organization_id: String,
    pub org_policy: std::option::Option<OrgPolicy>,
}
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct SetOrgPolicyResponse {
    pub request_id: String,
    #[serde(with = "http_serde::status_code")]
    pub status_code: http::StatusCode,
    pub org_policy: std::option::Option<OrgPolicy>,
}

pub struct Organizations {
    http_client: crate::client::Client,
}

impl Organizations {
    pub fn new(http_client: crate::client::Client) -> Self {
        Self {
            http_client: http_client.clone(),
        }
    }

    pub async fn get_org_policy(
        &self,
        body: GetOrgPolicyRequest,
    ) -> crate::Result<GetOrgPolicyResponse> {
        let organization_id = percent_encoding::utf8_percent_encode(
            &body.organization_id,
            percent_encoding::NON_ALPHANUMERIC,
        )
        .to_string();
        let path = format!(
            "/v1/b2b/rbac/organizations/{organization_id}?{}",
            serde_urlencoded::to_string(body).unwrap()
        );
        self.http_client
            .send(crate::Request {
                method: http::Method::GET,
                path,
                body: serde_json::json!({}),
            })
            .await
    }
    pub async fn set_org_policy(
        &self,
        body: SetOrgPolicyRequest,
    ) -> crate::Result<SetOrgPolicyResponse> {
        let organization_id = percent_encoding::utf8_percent_encode(
            &body.organization_id,
            percent_encoding::NON_ALPHANUMERIC,
        )
        .to_string();
        let path = format!("/v1/b2b/rbac/organizations/{organization_id}");
        self.http_client
            .send(crate::Request {
                method: http::Method::PUT,
                path,
                body,
            })
            .await
    }
}
